# Generated by Django 4.2.6 on 2023-10-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='xxx',
        ),
    ]
