# Generated by Django 4.2.6 on 2023-10-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_event_xxx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Cultural', 'Cultural'), ('Bhawan-Related', 'Bhawan-Related'), ('Misc.', 'Misc.')], max_length=120),
        ),
    ]
