# Generated by Django 4.2.6 on 2023-10-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
