# Generated by Django 4.2.6 on 2023-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bhawan_specifier',
            field=models.CharField(choices=[('All', 'All'), ('Rajendra', 'Rajendra'), ('Jawahar', 'Jawahar'), ('Rajiv', 'Rajiv'), ('Govind', 'Govind'), ('Ravindra', 'Ravindra'), ('Radhakrishnan', 'Radhakrishnan'), ('Kasturba', 'Kasturba'), ('Sarojini', 'Sarojini')], default='All', max_length=100),
        ),
    ]
